language: node_js
node_js: "12"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^renovate/.*$/
    - /^dependabot/.*$/

cache:
  directories:
    - node_modules

before_install:
  - npm install -g pnpm

install:
  - pnpm install

script:
	- pnpm run test
  - pnpm run build

after_script:
  - pnpm install -g codecov
  - codecov
